Repository JAMForHire/JAM-Final, pull requests merged in 2021-12, with the labels that each got.

#23 Implement foreign key
  .gitignore
  Resources/.DS_Store
  Resources/assets/.DS_Store
  components/jar.php
  dashboard.php
  register.php
  scripts/delete.js
  styles/style.css
Labels: enhancement

#22 Add and delete jars
  components/jar.php
  dashboard.php
  scripts/delete.js
Labels: enhancement

#24 Redesign Homepage
  Resources/assets/undraw_add_user.svg
  Resources/assets/undraw_login.svg
  index.php
Labels: enhancement

#32 Fixed Date Checking
  components/jar.php
  index.php
Labels: bug

#33 Fixed selection verification
  dashboard.php
Labels: bug

#34 Updated Company Name Text Color
  styles/style.css
Labels: bug

#35 Filter
  Resources/assets/chevron_down.svg
  components/jar.php
  config.php
  dashboard.php
  index.php
  styles/style.css
Labels: enhancement

#36 Redesign sidebar
  dashboard.php
Labels: enhancement

#38 Rounded User Pfp
  dashboard.php
  index.php
  uploads/26.jpeg
Labels: enhancement

#39 Added input sanitization
  Midterm Presentation.pdf
  README.md
  api/DB/db.php
  api/auth/login.php
  api/auth/logout.php
  dashboard.php
  export.txt
  jam.sql
  scripts/index.js
  styles/waves.png
Labels: bug

#40 Login and Register Sanitization
  Jam Final Presentation.pdf
  config.php
  login.php
  register.php
Labels: bug

#48 Bug fix
  components/jar.php
  dashboard.php
  register.php
Labels: bug

#49 Added max lengths
  components/jar.php
  dashboard.php
  register.php
Labels: bug

#50 Added Instructions
  README.md
  dashboard.php
Labels: documentation

#52 Added more details in readme
  README.md
Labels: documentation
